// Generated by CoffeeScript 1.10.0
var AWS, Client,
  slice = [].slice;

AWS = require('aws-sdk');

Client = (function() {
  function Client(options) {
    if (options == null) {
      options = {};
    }
    this.lambda = new AWS.Lambda(options);
  }

  Client.prototype.remote = function() {
    var args, cb, i, method, service;
    service = arguments[0], method = arguments[1], args = 4 <= arguments.length ? slice.call(arguments, 2, i = arguments.length - 1) : (i = 2, []), cb = arguments[i++];
    service = service.replace(':', '-');
    return this.lambda.invoke({
      FunctionName: service,
      Payload: JSON.stringify({
        method: method,
        args: args
      })
    }, function(err, data) {
      if (err != null) {
        console.log('[remote] Error:', err);
        return cb(err);
      } else {
        return cb(null, JSON.parse(data.Payload));
      }
    });
  };

  return Client;

})();

module.exports = {
  Client: Client
};
